### ISSUE TITLE
Add Uninstallation option

### ISSUE THREAD

**Issue by blueelvis** [exercism/windows-installer#1]
Right now, there is only installer, there is no way to uninstall the files without removing them completely.

Hurdles are -
- [ ] Create an uninstaller such that there is no trace left. The uninstaller itself should be deleted once it has completed it's operation.
- [ ] How to distribute the uninstaller?

One way of removing the uninstaller is using the `MoveFileEx` function. See here - https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx

**Comment by kytrinyx** [comment]
This doesn't answer any of the above questions, but for reference, there are two files:

- the exercism.exe executable
- the config file (usually `$HOME/.exercism.json` but people can change it with either `EXERCISM_CONFIG_FILE` or ,`XDG_CONFIG_HOME` as environment variables)

**Comment by blueelvis** [comment]
@kytrinyx - On using Exercism client, I have concluded that in order to make the uninstaller, it should have the following features -

- Create registry entries (So that it is visible in the Add/Remove Programs)
- It should remove the Configuration files, exercism client and the exercises (We can give users option about this one though)
- It should not leave any trace, i.e. it should delete itself after the uninstallation is complete (This is possible using Windows API).

**Comment by kytrinyx** [comment]
Yeah, that sounds like a good plan.

**Comment by kytrinyx** [comment]
I think this is probably still relevant.
