### ISSUE TITLE
windows-installer complaining about 7.0 32 bit not being compatible.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/windows-installer#13]
On my Windows 7.0 32 bit system I am greeted with the following upon executing `WinExercismSetup.exe`

![image](https://user-images.githubusercontent.com/6978003/28331182-19aabbd6-6bbe-11e7-91b0-9bfd59a2ce54.png)
 
The installer terminates when `OK` is clicked.  I am using the latest release `1.2`.

**Comment by rpottsoh** [comment]
I have forked this repo and managed to load up the project.  It appears to me that the installer was targeted for x64 instead of x86.

Once I rebuilt locally for x86 the installer worked fine.

/cc: @kytrinyx , @iHiD

**Comment by kytrinyx** [comment]
That's a great find. It seems like we should build two releases, then?

**Comment by rpottsoh** [comment]
I don't think it is necessary.  Just a 32 bit build should suffice.  64 bit windows will run 32 bit apps. 

There is no harm in having both, it just means that one has to be careful to download the right version. 

I am not familiar with how the installer decides which version of the CLI to download and install.  Is it based on flavor of Windows or the flavor of the installer's build.   At any rate 64 bit Windows will run 32 bit apps....



Sent from my android device.

**Comment by kytrinyx** [comment]
@rpottsoh Thanks! In that case I think we just need to make a new release of the 32 bit version. I've added you to the windows-installer team, giving you commit to this repository—in case you have spare cycles to cut a release (if you don't want to be on the team feel free to remove yourself!).

@blueelvis do you have time to cut a release with this change?

**Comment by rpottsoh** [comment]
@kytrinyx I would feel better if @blueelvis would cut the release.  I consider my mod to be more of a hack that did resolve my issue, but may not be the best way to resolve the issue long term.  I happen to have VS on my computer for some minor C++ coding I do at work, thus C# was available so I thought I would take a look at the Windows-Installer project to see if I could first build it (which was not a problem at all), then execute the installer from within VS to see what it might tell me.  VS told me the project was built for 64 bit Windows.  So it became a simple matter of looking around in VS to find a setting that controlled the target architecture of the build....  @blueelvis likely has a better, more elegant way, to control this setting.

To top it off I have never released anything on GitHub, so I would need to educate myself on the steps involved.

**Comment by kytrinyx** [comment]
@rpottsoh that sounds good! I merged it for now, and if we need to do something different, we can do that in a new PR.

> To top it off I have never released anything on GitHub, so I would need to educate myself on the steps involved.

I know that daunting feeling of trying to figure out the steps of something completely new. I'm exhausted just thinking about it.

Alright, I'm leaving this open for @blueelvis, and also we'll know what we can tell people if something like this comes up.

/cc @exercism/windows if anyone here feels comfortable with C# and release management, let me know and I'll add you to the team here.

**Comment by rpottsoh** [comment]
[1.2.1](https://github.com/exercism/windows-installer/releases) published.

**Comment by kytrinyx** [comment]
Thank you so much, @rpottsoh!
