### ISSUE TITLE
Error configuring CLI: Unhandled Exception

### ISSUE THREAD

**Issue by rpottsoh** [exercism/windows-installer#17]
@eunicesukarto commented on [Sat Jul 15 2017](https://github.com/exercism/exercism.io/issues/3589)

I have trouble installing the CLI. When I enter the API key during configuration, an error message shows up.
![capture](https://user-images.githubusercontent.com/28812327/28238220-2c56aa02-6979-11e7-9399-973a3a59fd9e.PNG)

If I click Continue, the error message shows up again. If I click Quit, it shuts down. What should I do?

---

@kytrinyx commented on [Sat Jul 15 2017](https://github.com/exercism/exercism.io/issues/3589#issuecomment-315553642)

@eunicesukarto I'm sorry you're running into this problem. I'm afraid I don't know what's going on.

@blueelvis do you know what's happening here?

In the meanwhile, you could try one of the other installation methods listed here: http://exercism.io/clients/cli/windows

---

@pelucky commented on [Sun Jul 16 2017](https://github.com/exercism/exercism.io/issues/3589#issuecomment-315605179)

@eunicesukarto Show the Details thing? It's seems some specific file can't find...

---

@eunicesukarto commented on [Tue Jul 18 2017](https://github.com/exercism/exercism.io/issues/3589#issuecomment-316108661)

@pelucky , the details are:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception: The system cannot find the file specified

Server stack trace: 
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ExercismWinSetup.ConfigureApi.Configure(String key)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData& msgData)
   at ExercismWinSetup.ConfigureApi.ConfigureApiDelegate.EndInvoke(IAsyncResult result)
   at ExercismWinSetup.ConfigureApi.nextButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
ExercismWinSetup
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/ExercismWinSetup.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/ExercismWinSetup.exe
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ZipStorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/ExercismWinSetup.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Thankss

---

@eunicesukarto commented on [Tue Jul 18 2017](https://github.com/exercism/exercism.io/issues/3589#issuecomment-316109383)

@kytrinyx thanks. I'll try to install from there.

---

@eunicesukarto commented on [Tue Jul 18 2017](https://github.com/exercism/exercism.io/issues/3589#issuecomment-316114256)

@kytrinyx thank you so much. The manual installation works :)

**Comment by rpottsoh** [comment]
ref: #16 
closes: exercism/exercism.io#3589

@eunicesukarto I am glad to read that you managed to manually install the windows CLI.  This past weekend I published an updated version of the Windows Installer [v 1.2.1](https://github.com/exercism/windows-installer/releases/latest) for the CLI.  While the update doesn't address this specific issue (I was not aware of it till today, I only started looking at this repo last week) I am curious to see if this latest build behaves any differently than the one you used 9 days ago.

You should be able to just run the installer.  If you do not want to jeopardize your present configuration then I recommend pointing the installer towards a different folder.  When prompted for your API key go ahead and input your legitimate key.

@eunicesukarto please let me know what version of Windows you are using?  Version 7 or 10, etc.  32 bit or 64 bit.

**Comment by assemusr** [comment]
@rpottsoh Thanks for your dedicated work. I used the lasted version you're referring to on (x64 Windows 8.1), and my error was similar to this one.

**Comment by rpottsoh** [comment]
I'll take a look at the code when I get a chance to see if I can see anything obvious.  I do not have access to 64 bit windows so I am not able to create the problem.  I do not see the error in 32 bit os.  At least I know that the problem was not affected by my release. 

@assemusr thanks for the feedback.

**Comment by rpottsoh** [comment]
@assemusr and @eunicesukarto I have been working on a new Windows Installer.  If you are willing to participate I could use some help by having someone try out the [Release Candidate](https://github.com/exercism/windows-installer/releases/tag/RC1) that I have published.

**Comment by assemusr** [comment]
This error popped up 

![capture](https://user-images.githubusercontent.com/16057969/28751292-4564fa8a-7504-11e7-8ec9-37f09fd81754.PNG)

**Comment by rpottsoh** [comment]
@assemusr thanks for the quick feedback!  I am not able to create this error here so this may be difficult to diagnose.  Anyway, I have made a minor change and published an update [here](https://github.com/rpottsoh/exercism-windows-installer/releases/tag/RC1.1) that you may try.   for the sake of testing you may want to consider installing to a different folder than the one you normally have the CLI installed.  In the end it won't matter.

**Comment by assemusr** [comment]
It doesn't actually matter, the Exercism folder is empty (the previous CLI didn't extract the zip file).

Anyway, the new installer extracted one file called 'exercism.exe' into the specified directory. But then again I couldn't continue the installation because of the API configuration.

![capture](https://user-images.githubusercontent.com/16057969/28753788-0a6c3e80-753a-11e7-835c-4719eb51944d.PNG)

**Comment by rpottsoh** [comment]
@assemusr I am able to recreate this error on my 64 bit machine, no problem on my 32 bit machine. 👍 I'll take a look.  I suspect my technique for spawning the CLI to `configure` itself is the issue.  I have another way to do it that should take care of this.  I'll let you know when I have another RC for you to try.  Thanks!

@kotp I am not sure if you are running 32 bit or 64 bit windows in your VM.  Still plan on testing [RC1.1](https://github.com/rpottsoh/exercism-windows-installer/releases/tag/RC1.1).

**Comment by kotp** [comment]
It would be nice if that error would identify what the file is that is "specified".

**Comment by rpottsoh** [comment]
It shows the name of the file in the image @assemusr posted.

**Comment by rpottsoh** [comment]
@assemusr and @kotp please try out [RC1.2](https://github.com/rpottsoh/exercism-windows-installer/releases/tag/RC1.2) please.  This version does work on my 64 bit Windows 10 system.  Thanks

**Comment by assemusr** [comment]
@rpottsoh Yeah, it works 😃 Thanks 😄 
Does this considered as full release? should I continue using it?

**Comment by rpottsoh** [comment]
The answer is yes and no. :smile_cat: 

Yes, you can use it, I am glad it finally worked for you.  

No it is not a release version.  I was planning to hold off on publishing a release until after Nextercism comes online.  I understand that there are some visual changes that I will want to make to the installer to better align its look to that of the new site.

I am not anticipating any functional changes to the installer at this point.  Thanks again for taking the time to test this out for me!  :1st_place_medal: 

/cc: @kytrinyx

**Comment by assemusr** [comment]
Great, I appreciate your help. 😄
