### ISSUE TITLE
Readme.md will need to be updated

### ISSUE THREAD

**Issue by rpottsoh** [exercism/windows-installer#21]
[Readme.md](https://github.com/exercism/windows-installer/blob/master/README.md) will need to be updated as the new installer is released.  The release will likely no happen until after Nextercism makes its debut.

**Comment by blueelvis** [comment]
Thanks for creating this issue. This got lost in my Github notifications :(

**Comment by rpottsoh** [comment]
No problem.  I hope you are not too offended but I have gone and written a new installer in Delphi.  I would be happy to work on it with you if you are willing.

cc: @kytrinyx

**Comment by blueelvis** [comment]
@rpottsoh - Offended? I should be the one saying sorry here. I am sorry about this. I just took quick peek at the latest release along with all the issues and PRs and thanks a lot. You have done excellent work! I actually enabled notifications for another project and their work spammed all of my notifications. I recently unfollowed them and saw this.

If you have some work for me, just assign it to me in the issues.

I just used the installer and it worked perfectly! Once again thanks!

**Comment by rpottsoh** [comment]
Thanks for being so gracious @blueelvis.  I am going to go ahead and close this issue as I have released a new version of the installer and updated the README.  This version of the installer should bridge the install process and work for the old and new CLI.
