### ISSUE TITLE
Should older releases be taken down?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/windows-installer#28]
@kytrinyx should older releases of the installer be taken down especially as Nextercism eventually goes public?

**Comment by kytrinyx** [comment]
I think we should leave them, but edit them to show a deprecation notice.

**Comment by rpottsoh** [comment]
>I think we should leave them, but edit them to show a deprecation notice.

@kytrinyx I'll work on this.  However, I would like to understand what the value is in keeping deprecated versions available for download.  Older versions will not be compatible with the v2 CLI, the final step the installer takes to configure the v1 CLI will be problematic for the v2 CLI.

**Comment by rpottsoh** [comment]
I have added a deprecation notice to the obsolete releases.  Let me know if you had something different in mind and I'll take care of it.

**Comment by kytrinyx** [comment]
That looks good to me. Thank you!
