### ISSUE TITLE
Exercism does not install if you used default install path or if install path typed directly in

### ISSUE THREAD

**Issue by michaeljohnstone** [exercism/windows-installer#3]
By code inspection, the installPath variable only gets populated when user uses the browse feature, so any user using the default location or by typing in a location will have their install fail with no feedback provided

**Comment by blueelvis** [comment]
@michaeljohnstone - Thanks buddy for reporting the issue. I have fixed the issue as of now. Please let me know if it still does not work ;)

https://github.com/blueelvis/ExercismWinSetup/commit/c26a2769b41d7e85c0cfae67fd2f4d7a243cc1c3

**Comment by michaeljohnstone** [comment]
Good work on the quick turn around!
Looking at your code check in you are checking a hardcoded string against the default value of installPath.Text which is set somewhere else - you should bring this out to some form of config/variable to remove the magicness of this string.

You also specifically check for this default directory and create it if it doesn't exist, which is redundant, is this check is done again in clientDownload.cs (lines 91-94). I think a simpler solution would be to just use line 40 and strip out lines 36-39.

P.s. I'm new to git so if there's a better way to comment on changes/do a code review, please let me know :)

**Comment by blueelvis** [comment]
Hi Michael ^_^,

Thanks a lot for the feedback. I really appreciate it. Could you please see the latest commit? I am new to these projects so...

Also, could you guide me how I could write Unit Tests for a project like this?

Regarding the code review, GitHub is absolutely fine. If you are comfortable with another method, let me know and I will see what can be done ;)

**Comment by blueelvis** [comment]
Marking this as fixed. Unit Tests are a separate topic.
