### ISSUE TITLE
Need to update EXE's icon from old logo to new logo.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/windows-installer#40]
@kytrinyx at some point  the icon for the installer needs to be updated.  Can you point me to the PNG or ICO file you would like me to use?

**Comment by rpottsoh** [comment]
@kytrinyx I came across this folder https://github.com/exercism/prototype/tree/master/app/assets/images in exercism/prototype.  I should be able to come up with what I need from here.

**Comment by kytrinyx** [comment]
So sorry I missed this, thank you for getting it sorted out!
