### ISSUE TITLE
When Installing the CLI with the installer, it removes user-defined path's in the environment variables

### ISSUE THREAD

**Issue by hp-e** [exercism/windows-installer#50]
Hi

When I installed the exercism cli on my windows machine today, it removed all the user-defined paths in the environment variables, it should append the exerxism to the list and not replacing the list.

I used the installer from the website (Delphi...?)

hp

**Comment by rpottsoh** [comment]
@hp-e I am sorry to hear that the installer gave you some grief.  What version of Windows are you using?  The installer is developed on a Windows 10 system and I also test it on a Windows 7 system.  I have nothing else to work with.  The source code is appending to the path and shouldn't be *erasing* your path information.

Can you tell me more about your system?  The code responsible for updating the path is in [this](https://github.com/exercism/windows-installer/blob/master/Delphi/Project/Source/uUpdatePath.pas) unit.

```pascal
class function TUpdatePath.AddToPath(aDir: string): Boolean;
var
    reg: TRegistry;
    openResult: Boolean;
    lPath: string;
begin
  result := false;
  reg := TRegistry.Create;
  try
    reg.RootKey := HKEY_CURRENT_USER;
    openResult := reg.OpenKeyReadOnly('Environment');
    if openResult then
    begin
      lPath:= reg.ReadString('Path');
      if lPath.ToLower.Contains(aDir.ToLower) then
        result := true
      else
      begin
        reg.CloseKey;
        reg.Access := KEY_WRITE;
        openResult := reg.OpenKey('Environment', true);
        if openResult then
        begin
          if not lPath.EndsWith(';') then
            lPath := lPath + ';';
          lPath := lPath + aDir;
          reg.WriteString('Path',lPath);
          BroadcastChange;
          result := true;
        end;
      end;
    end
    else
      result := false;
  finally
    reg.CloseKey;
    reg.Free;
  end;
end;
```

**Comment by hp-e** [comment]
@rpottsoh Thanks for answering :-)

About my machine
OS: MS Windows 10 Enterprise
Version: 10.0.15063 Build 15063
Machine: Fujitsu Lifebook U747, x64
Processor: i7-7500U

To me (a non pascal dev), your code looks correct and does exactly the same things that the code I published yesterday did.

Well, Today I did a reinstall to see if this was the installer or if it was a coincidence.

1) Added back all my missing patch
2) Reinstalling Exercism with the same installer as yesterday
3) Check environment Variables - All paths still there :-)
4) Configure the Exercism CLI (with `exercism configure --token=xxxxxxxxxxx`)
5) Check Environment Variables - all paths still there :-)
6) Redownloaded the code I was using as the exercise with `exercism download --exercise=hello-world --track=go`
7) Check Environment Variables - all paths still there :-)

I guess this was a system hiccup or a coincidence and I will, therefore, close the issue. 
I blamed this installer since the path of exercism was the only path in the Environment Variables.

Sorry :-(

Best Regards
Hans-Petter Eitvet

**Comment by rpottsoh** [comment]
No worries.  I am glad it all worked out OK for you the second time around.

I would like to not add to the path.  I can get away with this I think with Windows 10 but I don't think I can with Windows 7 (I don't know about version in between).  I am not aware of a folder that is always in the path that I can be assured will always be available for new files to be written to and not be blocked by access privileges.

In your case the only way I can reason that the PATH was obliterated would be because `reg.ReadString('Path')` yielded and empty string.  I am not currently testing for that occurence.  It would be pretty disconcerting if the underlying Windows API actually returned "nothing" when asked for `'Path'`.
