### ISSUE TITLE
Better instructions:

### ISSUE THREAD

**Issue by reactstl** [exercism/windows-installer#52]
(1) Download all three items.

(2) Open GitBash in the newly--and automatically!--created Exercism folder.

(3) Type this: exercism configure --token=YOUR_EXERCISM_TOKEN_WHICH_IS_SPECIFIC_TO_YOU
^
Assuming you are logged in, your Exercism token can be found at this page: http://exercism.io/my/settings

**Comment by rpottsoh** [comment]
Are you referring to the Walk-through or the Windows Installer?  They are two different things.  I am not sure how to relate what you have posted directly to the Windows Installer.  The repo for the walk-through may be found here https://github.com/exercism/interactive-cli-walkthrough

**Comment by rpottsoh** [comment]
I am closing this due to no response.  If you are still having an issue or have questions please feel free to ask.
