### ISSUE TITLE
cannot create readme.md while installing

### ISSUE THREAD

**Issue by halmai** [exercism/windows-installer#58]
I am trying to install exercism on a new win10. During the install I change the destination location to `C:\Program Files\exercism`, this is the way how I like to organize my files. 

As an administrator, I gave all the permission to every user for this directory. 

The installation dialog says it downloaded the zip and started to install it. After writing `"Unzipping CLI to C:\Program Files\exercism"` to the log, I get an error pop-up:

    Cannot create file "C:\Program Files\shell\README.md". The system cannot find the path specified.

Why does it want to write into this `C:\Program Files\shell` directory? It has nothing to do there. 

(I worked it around, I changed the destination to `C:\Program Files\exercism\exercism`. Now it created a directory `C:\Program Files\exercism\shell` which still seems to be incorrect but at least, I managed to install it.)

**Comment by rpottsoh** [comment]
The installer is a 32 bit executable.  I don't recommend placing it in program files.  The sole job of the installer is to download the appropriate version of the CLI for your system.

My recommendation is to stay away from the program files area and see if the issue goes away.

**Comment by rpottsoh** [comment]
The error message also does not appear to be generated by the installer but rather by the CLI.  It is generally considered a bad practice to work within program files.  The CLI may have been configured to place the files it download in this area.  Where work on exercises is stored should not be in program files.

**Comment by halmai** [comment]
I think if it is not supposed to run there then it explicitly should prohibit to be started from there. Such an error message should be displayed then: 

    You cannot run this program from the `Program Files` or `Program Files (x86)` directory.

This would be much better than a weird error message that does not explain anything.

But anyway, I cannot see any reason why I shouldn't place a program into the `Program Files` or `Program Files (x86)` directory. This is the place where I put all my programs.

Much rather, it seems to be that the destination of the `shell` directory, by accident, is one level up compared to the selected destination directory. I cannot try it now but I think if I leave the original destination `C:\Exercism` then it would create a `C:\shell` directory which is also wrong. It should be placed `C:\Exercism\shell` instead. Don't you think so?

**Comment by rpottsoh** [comment]
The installer is not creating or attempting to create the shell folder.  I suggest downloading the zip file manually from the exercism/CLI repo and see what it contains.  The installer simply downloads and extracts the zip to the folder you indicate and also adds the path indicated to PATH.

I am curious to know what you find if you let the installer install to the suggested location.


Sent from MailDroid

**Comment by halmai** [comment]
I am not sure which program wants to create the `shell` directory, the installer or the CLI. The only sure thing is that after starting the installer, I got the error message and it caused some head scratching to me. Regardless of whether this is a bug in the installer or the CLI, it would be nice to fix it. 

I already installed exercism as I wrote above, thus I don't want to poke my system anymore.

**Comment by rpottsoh** [comment]
How did you finally install the CLI?


Sent from MailDroid

**Comment by halmai** [comment]
> How did you finally install the CLI?

I wrote it in my first message, see the paragraph that starts with "I worked it around". :)

Basically, I installed it one level deeper so that the `../shell` directory still falls under the one I wanted to install the whole exercism software in.

**Comment by rpottsoh** [comment]
Ok, I'll review again later.  I am just going by what GitHub is feeding me via. email, I don't get to see previous posts to the issue that way.


Sent from MailDroid

**Comment by rpottsoh** [comment]
Unable to reproduce.
