### ISSUE TITLE
Failed to set data for 'path'

### ISSUE THREAD

**Issue by nhomble** [exercism/windows-installer#59]
Through the UI I tried to install exercism on my windows 10 machine [here](https://github.com/exercism/windows-installer/releases/tag/v1.5.3).

The installer has the following output
```
Fetching Version Info.
Successfully retrieved Version Info
Fetching Assets Info.
Successfully retrieved Assets Info
Fetching URL for latest CLI version.
Successfully retrieved URL
Downloading: "exercism.zip" (4139938 Bytes) into <folder>/exercism.zip
Download Finished!
Status: 200 - OK
Unzipping CLI to <folder>
CLI Extraction Successful
```
I have tried both installing to my ```C:``` drive and onto a separate disk (E:) where I have a separate bin folder of random executables I use.

Unfortunately, the pop up doesn't tell me much else to debug other than the error message in the title of the issue

**Comment by rpottsoh** [comment]
What is <folder>?  Please provide screen shot of error you see.

**Comment by nhomble** [comment]
![image](https://user-images.githubusercontent.com/3923558/65879291-88513d80-e35d-11e9-9a07-086f970eb395.png)

**Comment by rpottsoh** [comment]
What install location did you input on the first screen?  Have you tried running the installer as administrator?

**Comment by nhomble** [comment]
The image shows the inputted path "E:\bin" and running as admin doesn't work. 

As a side note, there's now way to exit the installer via the UI when I am in this state. "Finish" is greyed out. I have to right click the window on the windows toolbar.

**Comment by rpottsoh** [comment]
The installer has entered a state that I cannot duplicate and cannot easily detect.  Based on the error message it still appears like a permissions issue, even though you are running the installer as administrator.  If you are willing to dig into this a little bit more for me would you be willing to look into this https://support.microsoft.com/en-us/help/15078/windows-10-make-older-apps-or-programs-compatible for me.  These instructions may be useless, I have no way of knowing.

The installer is intended to be at least Windows 7 (and up) compatible.  My ability to test on versions of Windows less than 10 is very limited.

When you do manage to get out of the installer does a copy of `exercism.exe` exist at E:\bin?  Is E:\bin already in your path?

**Comment by nhomble** [comment]
Good news is ```exercism.exe``` does exist. If you dumped trace logs of the installation process I could debug it too. Up to you.
