### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by T1mL3arn** [exercism/windows-installer#60]
## What I did

1. Download windows installer
2. Install cli with it
3. Tried to uninstall ...

## What I got

Could not find the installed app in the OS software list to uninstall the app.

## What I expected

The presence of the app to be uninstalled. 

## Additional info

Similar #1 issue is closed. Is the feature not implemented ?

OS: WIndows 8.1 x64

**Comment by Anas966** [comment]
Please is there any way to uninstall exercism

**Comment by rpottsoh** [comment]
@Anas966 simply go to the folder to which you instructed the installer to install the CLI and delete `exercism.exe`.  The only thing the installer is doing is placing a copy of `exercism.exe` into the folder you indicated.

**Comment by NobbZ** [comment]
I'm not aware of how exactly the windows installer works, but usually there is some software corner in the windows settings, and it lists installed software. If the windows installer causes exercism to be listed there, then a proper uninstall option should be provided. If its not listed there, then just deleting the folder is technically sufficient, but still inconvinient.

We provided the installer in the first place to give a better user experience, and then having to delete the binary by hand is all but "a better experience".

**Comment by yihuajack** [comment]
You'd better also remove Exercism.exe from User Variables
