### ISSUE TITLE
Add configuration to ignore SSL certificate check and get proxy configuration

### ISSUE THREAD

**Issue by arlm** [exercism/windows-installer#62]
lease add the option of enabling and disabling certificate check for SSL connections. I have a proxy in the middle that changes the certificate and can't connect to the server. Also the option of using proxies or detecting the Internet Explorer configuration on that aspect.

If that is OK for all I can work on an PR for that on Delphi and C#, if the project supporters approves this feature request.

**Comment by rpottsoh** [comment]
You would need to use Delphi.  Code should build in latest CE version, which is free.

**Comment by arlm** [comment]
I don't really need this feature anymore, and am using macOS now.
