### ISSUE TITLE
Attempting to download Exercism exercise is successful on cmd but it does not appear on folder

### ISSUE THREAD

**Issue by marienneLopez** [exercism/windows-installer#65]
I installed and configured Exercism using the installer and I tried to get the Hello World exercise under Java. I am using a 64-bit Windows platform.

However, the cmd does say that it has downloaded the exercise to my folder but when I try to look up the folder, it does not exist.

**Comment by rpottsoh** [comment]
It sounds like you have installed the CLI correctly and are having an issue with the CLI and not the installer.  You should open an issue in the exercism/exercism repository for assistance with the CLI.

**Comment by Ladymoradi** [comment]
You can change the path to the exercism folder

**Comment by rpottsoh** [comment]
When you run the installer you can specify where the installer will install the CLI.  I don't know what you mean by the excercism folder.  It is possible that one may participate in more than one track.  You can install the CLI wherever you want, just make sure the Path is updated so Windows can find it.

There is also a manual installation walkthrough offered on the Excercism website.
