### ISSUE TITLE
Exercism is not added to path on Windows 10

### ISSUE THREAD

**Issue by sguermond** [exercism/windows-installer#7]
Installing the exercism CLI with the installer on Windows 10 does not add exercism.exe to the path, so you must go to the directory where exercism is installed to run it.

**Comment by blueelvis** [comment]
@sguermond - Thanks for the report. Let me see what is going wrong :)

**Comment by blueelvis** [comment]
Fixed this issue in this commit - https://github.com/exercism/windows-installer/commit/d3b7f893034381de33864d0a26be036d41f8d95c
