### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by kytrinyx** [exercism/windows-installer#8]
At the moment this is not open source, since it doesn't have a license.

@blueelvis Would you be happy using the MIT license for this? http://choosealicense.com/licenses/mit/

**Comment by blueelvis** [comment]
@kytrinyx Sorry for the lack of communication. Just started the job. And yes, I will implement this soon ;)

**Comment by kytrinyx** [comment]
Congrats on the new job!

**Comment by blueelvis** [comment]
@kytrinyx - Thanks a lot for the wishes. I am just setting up things. I have fixed this issue. You can check it out over here - https://github.com/exercism/windows-installer/blob/master/LICENSE

Please let me know in case any corrections are required. And thanks for the licensing website!

**Comment by kytrinyx** [comment]
Mike should not be a copyright holder. I would delete this: https://github.com/exercism/windows-installer/blob/master/LICENSE#L3

And on this https://github.com/exercism/windows-installer/blob/master/LICENSE#L4

I would suggest:
```
Copyright (c) 2017 Pranav V Jituri
```

This license is only for the Windows installer (this codebase) so it doesn't make sense to have the name of the software there.

**Comment by blueelvis** [comment]
@kytrinyx - Changes done. I have removed Line number 3 and edited line 4.

**Comment by kytrinyx** [comment]
Awesome, it looks great.
